apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-deployment
  labels:
    app: inventory
spec:
    replicas: 2
    selector:
       matchLabels:
         app: inventory
    template:
      metadata:
         labels:
           app: inventory
      spec:
         containers:
           - name: inventory
             image: __DOCKER_USER__/inventory:latest
             ports:
               - containerPort: 8083