services:
  inventory:
    build:
      context: .
      dockerfile: ./inventory/Dockerfile
    image: inventory:latest
    container_name: inventory
    ports:
      - "8083:8083"
    environment:
      SPRING_PROFILES_ACTIVE: local
    restart: always

  payment:
    build:
      context: .
      dockerfile: ./payment/Dockerfile
    image: payment:latest
    container_name: payment
    ports:
      - "8084:8084"
    environment:
      SPRING_PROFILES_ACTIVE: local
    restart: always

  gateway:
    build:
      context: .
      dockerfile: ./gateway/Dockerfile
    image: gateway:latest
    container_name: gateway
    ports:
      - "8082:8082"
    environment:
      SPRING_PROFILES_ACTIVE: local
      # Ensure your Spring Boot config uses the service names (e.g., 'inventory', 'payment')
    # Ensure gateway starts only after its dependencies
    depends_on:
      - inventory
      - payment
    restart: always